const $ = (id) => document.getElementById(id);
const SESSION_KEY = 'lumina-navigation-session';
const VOICE_KEY = 'lumina-navigation-voice';
const THRESHOLDS = [300, 100, 50];
const CATS = [['restaurant', '🍽️ Εστιατόρια'], ['pizza', '🍕 Πιτσαρίες / Fast food'], ['coffee', '☕ Καφέ'], ['gas_station', '⛽ Βενζίνη'], ['pharmacy', '💊 Φαρμακεία'], ['hotel', '🏨 Ξενοδοχεία'], ['parking', '🅿️ Parking'], ['supermarket', '🛒 Supermarket'], ['hospital', '🏥 Νοσοκομεία'], ['gym', '🏋️ Γυμναστήρια'], ['beach', '🏖️ Παραλίες']];
const CATQ = { restaurant: '["amenity"="restaurant"]', pizza: '["amenity"~"restaurant|fast_food"]', coffee: '["amenity"="cafe"]', gas_station: '["amenity"="fuel"]', pharmacy: '["amenity"="pharmacy"]', hotel: '["tourism"~"hotel|guest_house|apartment"]', parking: '["amenity"="parking"]', supermarket: '["shop"="supermarket"]', hospital: '["amenity"="hospital"]', gym: '["leisure"="fitness_centre"]', beach: '["natural"="beach"]' };
let pos = null, map = null, meMarker = null, route = null, routeLine = null, dest = null, destMarker = null;
let step = 0, navigating = false, spoken = new Set(), rerouting = false, arrived = false, heading = null, currentSpeed = 0, poiLayer = null, radarLayer = null, radars = [], lastAmbientFetch = 0, lastAmbientCenter = null;
let gpsWatchId = null, gpsRetryTimer = null, gpsState = 'waiting';
const GPS_OPTIONS = { enableHighAccuracy: true, timeout: 12000, maximumAge: 1500 };
const rad = (value) => value * Math.PI / 180;
const dist = (a, b) => { const R = 6371e3, p1 = rad(a.lat), p2 = rad(b.lat), dp = rad(b.lat - a.lat), dl = rad(b.lng - a.lng), x = Math.sin(dp / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dl / 2) ** 2; return 2 * R * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); };
const fd = (meters) => meters < 1000 ? `${Math.round(meters)} m` : `${(meters / 1000).toFixed(1)} km`;
let lastSpoken = '';
function say(text, priority = 'normal') { if (window.luminaVoiceEnabled === false || !('speechSynthesis' in window) || (priority !== 'critical' && navigating && speechSynthesis.speaking)) return; if (text === lastSpoken && speechSynthesis.speaking) return; lastSpoken = text; speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'el-GR'; utterance.rate = .95; utterance.onend = () => { if (lastSpoken === text) lastSpoken = ''; }; speechSynthesis.speak(utterance); }
window.luminaSay = say;
function osmPoint(element) { const lat = element.lat ?? element.center?.lat, lng = element.lon ?? element.center?.lon; return Number.isFinite(lat) && Number.isFinite(lng) ? { lat: +lat, lng: +lng } : null; }
function poiName(element) { return element.tags?.name || element.tags?.['name:el'] || element.tags?.brand || 'Σημείο'; }
function initMap() { if (map) return; map = L.map('map', { zoomControl: false, preferCanvas: true }).setView(pos ? [pos.lat, pos.lng] : [39.16, 20.98], pos ? 16 : 7); L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '© OpenStreetMap contributors' }).addTo(map); L.control.zoom({ position: 'bottomright' }).addTo(map); poiLayer = L.layerGroup().addTo(map); radarLayer = L.layerGroup().addTo(map); map.on('moveend', refreshAmbientPois); refreshAmbientPois(); }
function setMe() { if (!map || !pos) return; if (!meMarker) meMarker = L.circleMarker([pos.lat, pos.lng], { radius: 8, color: '#fff', weight: 3, fillColor: '#1d8cff', fillOpacity: 1 }).addTo(map); else meMarker.setLatLng([pos.lat, pos.lng]); }
function hidePois() { if (map && poiLayer && map.hasLayer(poiLayer)) map.removeLayer(poiLayer); }
function restorePois() { if (map && poiLayer && !map.hasLayer(poiLayer)) poiLayer.addTo(map); }
function gpsErrorMessage(error) { if (error?.code === 1) return 'Η πρόσβαση στην τοποθεσία είναι μπλοκαρισμένη. Ενεργοποίησέ την από τις ρυθμίσεις του browser.'; if (error?.code === 3) return 'Η λήψη GPS έληξε λόγω timeout. Δοκίμασε ξανά.'; if (error?.code === 2) return 'Οι υπηρεσίες τοποθεσίας δεν είναι διαθέσιμες. Έλεγξε το GPS και δοκίμασε ξανά.'; return 'Δεν ήταν δυνατή η λήψη θέσης GPS. Δοκίμασε ξανά.'; }
function setGpsStatus(message, state = 'error') { gpsState = state; $('gps').textContent = state === 'active' && pos ? `GPS ενεργό · ±${Math.round(pos.accuracy || 0)}m` : state === 'checking' ? 'GPS…' : 'GPS ✕'; $('status').textContent = message; $('gpsAction').classList.toggle('hidden', state === 'active'); }
function applyPosition(location) { const coords = location.coords; pos = { lat: coords.latitude, lng: coords.longitude, accuracy: coords.accuracy, timestamp: location.timestamp }; heading = Number.isFinite(coords.heading) ? coords.heading : heading; currentSpeed = Number.isFinite(coords.speed) && coords.speed >= 0 ? Math.round(coords.speed * 3.6) : 0; setGpsStatus(`GPS ενεργό · ±${Math.round(coords.accuracy || 0)}m`, 'active'); initMap(); const wasMissing = !meMarker; setMe(); if (map && wasMissing) map.setView([pos.lat, pos.lng], 17); else if (map && navigating) map.setView([pos.lat, pos.lng], 17, { animate: true }); updateNav(); refreshAmbientPois(); }
function scheduleGpsRetry() { clearTimeout(gpsRetryTimer); gpsRetryTimer = setTimeout(startGps, 15000); }
async function checkGpsPermission() { if (!navigator.permissions?.query) return 'unknown'; try { return (await navigator.permissions.query({ name: 'geolocation' })).state; } catch { return 'unknown'; } }
async function startGps() { clearTimeout(gpsRetryTimer); if (!navigator.geolocation) { setGpsStatus('Αυτός ο browser δεν υποστηρίζει GPS.', 'error'); return; } const permission = await checkGpsPermission(); if (permission === 'denied') { setGpsStatus('Η πρόσβαση στην τοποθεσία είναι μπλοκαρισμένη. Ενεργοποίησέ την από τις ρυθμίσεις του browser.', 'error'); return; } setGpsStatus('Ζητώ άδεια και θέση GPS…', 'checking'); navigator.geolocation.getCurrentPosition(applyPosition, (error) => { setGpsStatus(gpsErrorMessage(error), 'error'); if (error.code !== 1) scheduleGpsRetry(); }, GPS_OPTIONS); if (gpsWatchId == null) gpsWatchId = navigator.geolocation.watchPosition(applyPosition, (error) => { setGpsStatus(gpsErrorMessage(error), 'error'); if (error.code !== 1) scheduleGpsRetry(); }, GPS_OPTIONS); }
async function overpass(query) { const response = await fetch(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(query)}`); if (!response.ok) throw Error('Η υπηρεσία σημείων δεν απάντησε.'); return response.json(); }
function show(items) { const visible = items.sort((a, b) => a.distance - b.distance).slice(0, 30); $('results').innerHTML = ''; if (poiLayer) { poiLayer.clearLayers(); visible.forEach((item) => L.circleMarker([item.point.lat, item.point.lng], { radius: 5, color: '#75d0ff', fillColor: '#168cff', fillOpacity: .8 }).bindTooltip(item.name).addTo(poiLayer)); } visible.forEach((item) => { const button = document.createElement('button'); button.className = 'result'; button.innerHTML = `<b>${item.name}</b><span>${fd(item.distance)} · ${item.address || ''}</span>`; button.onclick = () => calc(item); $('results').appendChild(button); }); $('status').textContent = visible.length ? `${visible.length} αποτελέσματα` : 'Δεν βρέθηκαν σημεία.'; return visible; }
async function geocodeCity(city) { const response = await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=gr&limit=1&featuretype=city&q=${encodeURIComponent(city)}`, { headers: { Accept: 'application/json' } }); if (!response.ok) throw Error('Δεν μπόρεσα να βρω την περιοχή.'); const data = await response.json(); const item = data?.[0]; return item ? { lat: +item.lat, lng: +item.lon } : null; }
async function category(id, city = null) { const center = city ? await geocodeCity(city) : pos; if (!center) { $('status').textContent = city ? `Δεν βρήκα την περιοχή ${city}.` : 'Περιμένω GPS…'; return []; } try { const data = await overpass(`[out:json][timeout:15];nwr${CATQ[id]}(around:12000,${center.lat},${center.lng});out center tags 60;`); return show((data.elements || []).map((element) => { const point = osmPoint(element); return point ? { id: `osm-${element.type}-${element.id}`, name: poiName(element), address: '', point, distance: dist(center, point) } : null; }).filter(Boolean)); } catch (error) { $('status').textContent = error.message || 'Σφάλμα αναζήτησης'; return []; } }
async function search(query = $('search').value.trim()) { if (!query) return []; try { const response = await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=gr&limit=10&addressdetails=1&q=${encodeURIComponent(query)}`, { headers: { Accept: 'application/json' } }); const data = await response.json(); return show((data || []).map((item) => { const point = { lat: +item.lat, lng: +item.lon }; return { id: `nom-${item.place_id}`, name: item.name || item.display_name?.split(',')[0] || query, address: item.display_name || '', point, distance: pos ? dist(pos, point) : 0 }; })); } catch (error) { $('status').textContent = error.message || 'Σφάλμα αναζήτησης'; return []; } }
function greekInstruction(stepData) { const maneuver = stepData?.maneuver || {}; const type = maneuver.type || ''; const modifier = maneuver.modifier || ''; if (type === 'roundabout' || type === 'rotary') { const exit = Number(maneuver.exit || 0); return { icon: '⟳', action: exit ? `ΚΥΚΛΙΚΟΣ ΚΟΜΒΟΣ · ${exit}η ΕΞΟΔΟΣ` : 'ΚΥΚΛΙΚΟΣ ΚΟΜΒΟΣ', voice: exit ? `Στον κυκλικό κόμβο, πάρτε την ${exit}η έξοδο.` : 'Μπείτε στον κυκλικό κόμβο.' }; } if (type === 'merge' || type === 'fork') return modifier.includes('left') ? { icon: '↰', action: 'ΚΡΑΤΗΘΕΙΤΕ ΑΡΙΣΤΕΡΑ', voice: 'Κρατηθείτε αριστερά.' } : { icon: '↱', action: 'ΚΡΑΤΗΘΕΙΤΕ ΔΕΞΙΑ', voice: 'Κρατηθείτε δεξιά.' }; if (type === 'uturn' || modifier === 'uturn') return { icon: '↶', action: 'ΚΑΝΕΤΕ ΑΝΑΣΤΡΟΦΗ', voice: 'Κάντε αναστροφή όπου επιτρέπεται.' }; if (modifier.includes('left')) return { icon: '↰', action: 'ΣΤΡΟΦΗ ΑΡΙΣΤΕΡΑ', voice: 'Στρίψτε αριστερά.' }; if (modifier.includes('right')) return { icon: '↱', action: 'ΣΤΡΟΦΗ ΔΕΞΙΑ', voice: 'Στρίψτε δεξιά.' }; return { icon: '↑', action: 'ΣΥΝΕΧΙΣΤΕ ΕΥΘΕΙΑ', voice: 'Συνεχίστε ευθεία.' }; }
async function calc(destination, silent = false) { if (!pos || !destination) return false; dest = destination; if (!silent) $('status').textContent = 'Υπολογίζω διαδρομή…'; try { const response = await fetch(`https://router.project-osrm.org/route/v1/driving/${pos.lng},${pos.lat};${destination.point.lng},${destination.point.lat}?overview=full&geometries=geojson&steps=true&alternatives=false`), data = await response.json(), first = data.routes?.[0]; if (!response.ok || !first) throw Error('Δεν βρέθηκε διαδρομή.'); route = { ...first, steps: first.legs?.[0]?.steps || [] }; drawRoute(); $('routeInfo').textContent = `${destination.name} · ${fd(first.distance)} · ${Math.max(1, Math.round(first.duration / 60))} λεπ`; $('routeCard').classList.remove('hidden'); if (!silent) $('status').textContent = 'Διαδρομή έτοιμη'; return true; } catch (error) { $('status').textContent = error.message || 'Δεν βρέθηκε διαδρομή.'; return false; } }
function drawRoute() { if (!map || !route) return; if (routeLine) map.removeLayer(routeLine); routeLine = L.polyline(route.geometry.coordinates.map((coordinate) => [coordinate[1], coordinate[0]]), { color: '#168cff', weight: navigating ? 10 : 7, opacity: .96 }).addTo(map); if (destMarker) map.removeLayer(destMarker); if (dest) destMarker = L.marker([dest.point.lat, dest.point.lng]).addTo(map); if (!navigating) map.fitBounds(routeLine.getBounds(), { padding: [55, 55] }); }
function saveSession() { if (!navigating || !route || !dest) { localStorage.removeItem(SESSION_KEY); return; } localStorage.setItem(SESSION_KEY, JSON.stringify({ version: 1, active: true, destination: dest, route, step, voiceEnabled: window.luminaVoiceEnabled !== false, savedAt: Date.now() })); }
function restoreSession() { let saved; try { saved = JSON.parse(localStorage.getItem(SESSION_KEY) || 'null'); } catch { return; } if (!saved?.active || !saved.destination || !saved.route) return; dest = saved.destination; route = saved.route; step = Math.min(Math.max(0, Number(saved.step) || 0), Math.max(0, route.steps.length - 1)); window.luminaVoiceEnabled = saved.voiceEnabled !== false; navigating = true; document.body.classList.add('navigating'); hidePois(); $('turn').classList.remove('hidden'); drawRoute(); $('status').textContent = 'Η καθοδήγηση συνεχίζεται'; updateNav(); }
function stopNavigation() { navigating = false; route = null; dest = null; step = 0; spoken.clear(); arrived = false; localStorage.removeItem(SESSION_KEY); document.body.classList.remove('navigating'); $('turn').classList.add('hidden'); $('navPanel').classList.add('hidden'); $('routeCard').classList.add('hidden'); if (routeLine) { map.removeLayer(routeLine); routeLine = null; } if (destMarker) { map.removeLayer(destMarker); destMarker = null; } speechSynthesis?.cancel(); restorePois(); $('status').textContent = 'GPS ενεργό'; }
function startNavigation() { if (!route) return; navigating = true; arrived = false; step = 0; spoken.clear(); document.body.classList.add('navigating'); hidePois(); $('turn').classList.remove('hidden'); $('navPanel').classList.remove('hidden'); say('Η καθοδήγηση ξεκίνησε.'); saveSession(); drawRoute(); updateNav(); }
function routeDeviation() { if (!route?.geometry?.coordinates?.length || !pos) return 0; return route.geometry.coordinates.reduce((best, coordinate) => Math.min(best, dist(pos, { lng: coordinate[0], lat: coordinate[1] })), Infinity); }
async function maybeReroute() { if (!navigating || rerouting || !dest || routeDeviation() < 110) return; rerouting = true; $('status').textContent = 'Επαναϋπολογίζω διαδρομή…'; say('Επαναϋπολογισμός διαδρομής.'); if (await calc(dest, true)) { step = 0; spoken.clear(); saveSession(); $('status').textContent = 'Καθοδήγηση ενεργή'; } rerouting = false; }
function updateNav() { if (!navigating || !pos || !route) return; const current = route.steps[step], location = current?.maneuver?.location; if (!location) return; const meters = dist(pos, { lng: location[0], lat: location[1] }), instruction = greekInstruction(current); $('turnIcon').textContent = instruction.icon; $('turnText').textContent = `${Math.max(10, Math.round(meters / 10) * 10)} μ. — ${instruction.action}`; $('turnMeta').textContent = current.name || ''; $('navTime').textContent = `${Math.max(1, Math.round(route.duration / 60))} λεπ`; $('navDistance').textContent = fd(route.distance); $('navEta').textContent = `ETA ${new Date(Date.now() + route.duration * 1000).toLocaleTimeString('el-GR', { hour: '2-digit', minute: '2-digit' })}`; for (const threshold of THRESHOLDS) { const key = `${step}:${threshold}`; if (meters <= threshold && !spoken.has(key)) { spoken.add(key); say(`${threshold > 50 ? `Σε ${threshold} μέτρα, ` : ''}${instruction.voice}`); } } if (meters < 28 && step < route.steps.length - 1) { step += 1; spoken.clear(); updateNav(); } if (dest && dist(pos, dest.point) < 30 && !arrived) { arrived = true; say('Έφτασες στον προορισμό σου.'); stopNavigation(); return; } saveSession(); maybeReroute(); }
function refreshAmbientPois() { return; }
CATS.forEach(([id, label]) => { const button = document.createElement('button'); button.textContent = label; button.onclick = () => { category(id); $('nearbyOptions').classList.add('hidden'); $('nearbyToggle').setAttribute('aria-expanded', 'false'); }; $('cats').appendChild(button); });
$('nearbyToggle').onclick = () => { const options = $('nearbyOptions'), open = options.classList.toggle('hidden') === false; $('nearbyToggle').setAttribute('aria-expanded', String(open)); if (!open) { $('results').innerHTML = ''; if (poiLayer) poiLayer.clearLayers(); } };
$('searchBtn').onclick = search; $('search').onkeydown = (event) => { if (event.key === 'Enter') search(); }; $('startBtn').onclick = startNavigation; $('stopBtn').onclick = stopNavigation;
function setTheme(theme) { document.documentElement.dataset.theme = theme; localStorage.setItem('lumina-theme', theme); }
function initSettings() { const settings = $('settings'); $('settingsBtn').onclick = () => { settings.classList.toggle('hidden'); settings.setAttribute('aria-hidden', String(settings.classList.contains('hidden'))); }; $('settingsClose').onclick = () => { settings.classList.add('hidden'); settings.setAttribute('aria-hidden', 'true'); }; $('gpsRetry').onclick = startGps; $('gpsAction').onclick = startGps; const voiceSetting = $('voiceSetting'); voiceSetting.checked = localStorage.getItem(VOICE_KEY) !== 'off'; voiceSetting.onchange = () => { window.luminaVoiceEnabled = voiceSetting.checked; localStorage.setItem(VOICE_KEY, voiceSetting.checked ? 'on' : 'off'); if (!voiceSetting.checked) speechSynthesis?.cancel(); }; const handsfree = $('handsfreeSetting'); handsfree.checked = localStorage.getItem('lumina-handsfree') === 'on'; handsfree.onchange = () => { localStorage.setItem('lumina-handsfree', handsfree.checked ? 'on' : 'off'); window.luminaSetHandsfree?.(handsfree.checked); }; const wakeWord = $('wakeWordSetting'); wakeWord.checked = localStorage.getItem('lumina-wake-word') !== 'off'; wakeWord.onchange = () => localStorage.setItem('lumina-wake-word', wakeWord.checked ? 'on' : 'off'); const theme = $('themeSetting'); theme.value = localStorage.getItem('lumina-theme') || 'auto'; setTheme(theme.value); theme.onchange = () => setTheme(theme.value); $('testVoice').onclick = () => window.luminaSay?.('Η φωνητική καθοδήγηση λειτουργεί.', 'critical'); $('testGps').onclick = () => startGps(); $('recenterBtn').onclick = () => window.luminaJulieAction?.({ type: 'recenter' }); $('clearToken').onclick = () => { localStorage.removeItem('mapbox-token'); $('status').textContent = 'Το προαιρετικό token διαγράφηκε.'; }; }

async function safetyQuery() { if (!pos) return 'Δεν έχω διαθέσιμη θέση GPS για έλεγχο ασφαλείας.'; try { const data = await overpass(`[out:json][timeout:12];node["highway"="speed_camera"](around:12000,${pos.lat},${pos.lng});out body;`); const cameras = (data.elements || []).filter((item) => Number.isFinite(item.lat) && Number.isFinite(item.lon)); if (!cameras.length) return 'Δεν βρήκα καταγεγραμμένη σταθερή κάμερα κοντά σου. Δεν έχω επαληθευμένα δεδομένα για κινητά ραντάρ ή αστυνομικούς ελέγχους.'; cameras.slice(0, 10).forEach((item) => L.circleMarker([item.lat, item.lon], { radius: 6, color: '#ffce72', fillColor: '#d98d24', fillOpacity: .9 }).bindTooltip('Σταθερή κάμερα').addTo(radarLayer)); return `Βρήκα ${cameras.length} καταγεγραμμέν${cameras.length === 1 ? 'η' : 'ες'} σταθερ${cameras.length === 1 ? 'ή κάμερα' : 'ές κάμερες'} κοντά σου. Δεν έχω επαληθευμένα δεδομένα για κινητά ραντάρ ή αστυνομικούς ελέγχους.`; } catch { return 'Δεν μπόρεσα να ελέγξω τα δεδομένα σταθερών καμερών αυτή τη στιγμή.'; } }
window.luminaJulieAction = async (intent) => { if (intent.type === 'stop_navigation') { stopNavigation(); return 'Η πλοήγηση σταμάτησε.'; } if (intent.type === 'start_navigation') { startNavigation(); return route ? 'Ξεκινάω την καθοδήγηση.' : 'Δεν υπάρχει έτοιμη διαδρομή.'; } if (intent.type === 'safety_query') return safetyQuery(); if (intent.type === 'current_status') return pos ? `Βρίσκεσαι περίπου στις ${pos.lat.toFixed(4)} μοίρες βόρεια και ${pos.lng.toFixed(4)} μοίρες ανατολικά.` : 'Περιμένω σήμα GPS.'; if (intent.type === 'recenter') { if (map && pos) map.setView([pos.lat, pos.lng], 17); return pos ? 'Κέντραρα τον χάρτη στη θέση σου.' : 'Περιμένω σήμα GPS.'; } if (intent.type === 'poi_search' || intent.type === 'nearby_destination') { const items = await category(intent.category, intent.city); if (!items.length) return 'Δεν βρήκα σχετικά σημεία.'; if (intent.openNow) return `Βρήκα ${items.length} σημεία, αλλά δεν έχω αξιόπιστη πληροφορία για το ποια είναι ανοιχτά αυτή τη στιγμή.`; const names = items.slice(0, 3).map((item) => item.name).join(', '); if (intent.type === 'nearby_destination') { await calc(items[0]); return `Βρήκα το κοντινότερο σημείο, ${items[0].name}, και ετοίμασα τη διαδρομή.`; } return `Βρήκα ${items.length} σημεία. Τα πιο σχετικά είναι ${names}. Πες μου το όνομα αν θέλεις να ξεκινήσω πλοήγηση.`; } if (intent.type === 'destination_search') { const items = await search(intent.query); return items.length ? `Βρήκα ${items.length} αποτελέσματα για ${intent.query}.` : 'Δεν βρήκα αυτόν τον προορισμό.'; } return 'Δεν κατάλαβα την εντολή. Μπορείς να ζητήσεις καφέ, πιτσαρίες, διαδρομή, κάμερες ή την τρέχουσα θέση σου.'; };
initSettings(); initMap(); restoreSession(); startGps(); window.luminaGpsTest = { success: applyPosition, error: (error) => setGpsStatus(gpsErrorMessage(error), 'error'), update: applyPosition }; window.addEventListener('visibilitychange', () => document.visibilityState === 'hidden' ? saveSession() : (restoreSession(), updateNav(), startGps())); window.addEventListener('pagehide', saveSession); window.addEventListener('pageshow', () => { restoreSession(); updateNav(); startGps(); }); window.addEventListener('focus', () => { restoreSession(); updateNav(); });
